---
title: "R Notebook"
output: html_notebook
---


```{r}
library(dplyr)
musica <- read.csv("musica.csv")

musica

```
```{r}

sum(!complete.cases(musica))

```

```{r}

nrow(musica)

```

```{r}
summary(musica)
```


```{r}

sd(musica$Descargas)

```

```{r}
levels(musica$Pais)
```
```{r}

mean((musica[complete.cases(musica$Descargas),])$Descargas)



```
```{r}

min((musica[complete.cases(musica$Descargas),])$Descargas)

```

```{r}
median((musica[complete.cases(musica$Descargas),])$Descargas)
```


```{r}
sd(musica$Descargas)/mean((musica[complete.cases(musica$Descargas),])$Descargas)
```
```{r}

max((musica[complete.cases(musica$Descargas),])$Descargas)

```
```{r}
nrow(filter(musica, Pais!="global"))
```
```{r}
nrow(filter(musica, Pais=="global"))
```

```{r}
max_pais<- which.max(musica$Descargas)
max_pais

```

```{r}

music_singlobla <- filter(musica, Pais != "global")

```
```{r}
max_pais<- which.max(music_singlobla$Descargas)
```

```{r}
music_singlobla[max_pais,1:6]
```
```{r}
min_pais <- which.min(music_singlobla$Descargas)
min_pais
```

```{r}
music_singlobla[min_pais,1:6]
```
```{r}
table(musica$Fecha)
```

```{r}
max_pais<- which.max(musica$Descargas)
musica[max_pais,2]
```
```{r}
data_despacito <- subset(musica, regexpr("Despacito", musica$Cancion) > 0)
summary(data_despacito)
```




```{r}
tabla_salsa <- filter(musica, Cancion =="Despacito - Versión Salsa")

max_pais_des<- which.max(tabla_salsa$Descargas)
tabla_salsa[max_pais_des,6]
```
```{r}
peru <-  filter(musica, Cancion =="Despacito - Versión Salsa" & Pais == "pe")
mean(peru$Descargas)
```
```{r}
max_per<- which.max(peru$Descargas)
tabla_salsa[max_pais_des,1]
```

```{r}
summary(peru)
```

